import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-model',
  standalone: true,
  imports: [ReactiveFormsModule, CommonModule],
  templateUrl: './model.component.html',
  styleUrls: ['./model.component.scss']
})
export class ModelComponent {
  scanForm: FormGroup;
  submitted = false;
  loading = false;
  selectedFile: File | null = null;
  imagePreview: string | ArrayBuffer | null = null;
  analysisResult: string | null = null;

  constructor(private fb: FormBuilder) {
    this.scanForm = this.fb.group({
      patientId: [''], // No validators
      scanType: [''],  // No validators
      scanImage: ['', Validators.required] // Only image is required
    });
  }

  get f() {
    return this.scanForm.controls;
  }

  onFileSelected(event: Event) {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files.length > 0) {
      const file = input.files[0];
      
      // Clear previous errors
      this.scanForm.controls['scanImage'].setErrors(null);

      // Validate file type
      if (!file.type.match(/image\/(jpeg|png)/)) {
        this.scanForm.controls['scanImage'].setErrors({'invalidType': true});
        return;
      }

      // Validate file size
      if (file.size > 5 * 1024 * 1024) {
        this.scanForm.controls['scanImage'].setErrors({'invalidSize': true});
        return;
      }

      // Update form
      this.selectedFile = file;
      this.scanForm.patchValue({ scanImage: file });
      this.scanForm.get('scanImage')?.updateValueAndValidity();

      // Create preview
      const reader = new FileReader();
      reader.onload = () => {
        this.imagePreview = reader.result;
      };
      reader.readAsDataURL(file);
    }
  }

  generateDescription() {
    this.submitted = true;
    this.analysisResult = null;

    if (this.scanForm.invalid) {
      console.warn('Form is invalid:', this.scanForm.errors);
      return;
    }

    this.loading = true;
    
    setTimeout(() => {
      this.loading = false;
      this.analysisResult = `
        X-RAY ANALYSIS REPORT
        ---------------------
        ${this.scanForm.value.patientId ? `Patient ID: ${this.scanForm.value.patientId}` : ''}
        ${this.scanForm.value.scanType ? `Scan Type: ${this.scanForm.value.scanType.toUpperCase()}` : ''}
        Date: ${new Date().toLocaleDateString()}
        
      Chest CT. Chest CT shows an irregular contours mass in anterior mediastinum with mild heterogenetic enhancement (white arrow)
        
        Generated by XpeRay AI on ${new Date().toLocaleString()}
      `;
    }, 2000);
  }
}